import type { RegionSpec } from "@/lib/eligibility/region";

/**
 * Youth Center (온통청년) `zipCd` -> Damoa `RegionSpec` crosswalk.
 *
 * `zipCd` has NO entry in the official 온통청년 코드정의서 XLSX (still true —
 * see `provenance.ts`'s `ZIP_CD_PROVENANCE`, which this does NOT contradict).
 * This crosswalk resolves it from a DIFFERENT, independently-authoritative
 * source instead: the Korean government's own 법정동코드 전체자료 dataset (see
 * `YOUTH_ZIPCD_CROSSWALK_PROVENANCE` below for the exact file/hash/row
 * counts). `zipCd`'s raw values are 5-digit 시군구코드 — the first 5 digits of
 * that dataset's 10-digit 법정동코드 for every 시군구급 row (읍면동=000, 리=00).
 *
 * All 261 distinct raw `zipCd` tokens observed in the frozen 2,745-record
 * Youth catalog snapshot (see docs/audits — the Phase-1 join audit) were
 * independently classified against that dataset with ZERO unmapped tokens:
 *
 *   - 217 tokens: ordinary current leaf 시/군/구 (or 세종특별자치시 itself,
 *     which has no subordinate city) -> plain `{ province, city }` (or just
 *     `{ province }` for Sejong).
 *   - 39 tokens: current SUBORDINATE gu of one of the 13 gu-bearing 일반시
 *     (수원시, 성남시, 안양시, 부천시, 안산시, 고양시, 용인시, 화성시, 청주시,
 *     천안시, 포항시, 창원시, 전주시) -> `{ province, city, subdivision }`.
 *     Deliberately NOT collapsed to a plain city-level spec: Damoa profiles
 *     never record which gu of these 13 cities a user lives in, so
 *     collapsing would silently promote every resident of the whole city to
 *     a PASS even though the policy only covers one gu — see
 *     `lib/eligibility/region.ts`'s `RegionSpec.subdivision` doc and
 *     `domain/region/subdivisionPartition.ts` for the full constraint-
 *     compatibility reasoning and the OR-union completion mechanism that
 *     still lets an exhaustive multi-gu OR-list resolve to PASS.
 *   - 2 tokens: the 13 cities' own explicit PARENT-aggregate 법정동코드
 *     (41590=화성시, 44130=천안시) -> plain `{ province, city }` (these two
 *     codes represent the WHOLE city, not a specific gu, so an ordinary
 *     city-level spec is correct here, not `subdivision`).
 *   - 3 tokens: historical/폐지 codes (28110/28140/28260 = old 인천 중구/동구/
 *     서구, abolished 2026-07-01) -> plain `{ province: "인천광역시", city }`
 *     using the OLD district name. Fed as-is through the EXISTING
 *     `domain/region/adminTransition.ts` machinery (via `matchRegion`) —
 *     NOT aliased to a single current district, since old 중구/동구/서구 each
 *     overlap multiple current districts in different ways (see that
 *     module's hand-verified fact tables).
 *
 * Metropolitan/autonomous districts that Damoa already treats as city-level
 * units (Seoul's 25 gu, Incheon's current 제물포구/영종구/검단구/서해구/etc.,
 * 전남광주통합특별시's 동구/서구/남구/북구/광산구) are NEVER given a
 * `subdivision` — they're already `CURRENT_RESIDENCE_GAZETTEER`'s
 * selectable city-level granularity, so an ordinary `{ province, city }`
 * spec is correct and sufficient for them.
 *
 * This table is intentionally the ONLY place `zipCd` values are interpreted.
 * It was generated by parsing the official dataset — never derived from
 * policy titles, provider/institution names, or prefix-based guessing.
 */
export const YOUTH_ZIPCD_CROSSWALK: Record<string, RegionSpec> = {
  "11110": { province: "서울특별시", city: "종로구" },
  "11140": { province: "서울특별시", city: "중구" },
  "11170": { province: "서울특별시", city: "용산구" },
  "11200": { province: "서울특별시", city: "성동구" },
  "11215": { province: "서울특별시", city: "광진구" },
  "11230": { province: "서울특별시", city: "동대문구" },
  "11260": { province: "서울특별시", city: "중랑구" },
  "11290": { province: "서울특별시", city: "성북구" },
  "11305": { province: "서울특별시", city: "강북구" },
  "11320": { province: "서울특별시", city: "도봉구" },
  "11350": { province: "서울특별시", city: "노원구" },
  "11380": { province: "서울특별시", city: "은평구" },
  "11410": { province: "서울특별시", city: "서대문구" },
  "11440": { province: "서울특별시", city: "마포구" },
  "11470": { province: "서울특별시", city: "양천구" },
  "11500": { province: "서울특별시", city: "강서구" },
  "11530": { province: "서울특별시", city: "구로구" },
  "11545": { province: "서울특별시", city: "금천구" },
  "11560": { province: "서울특별시", city: "영등포구" },
  "11590": { province: "서울특별시", city: "동작구" },
  "11620": { province: "서울특별시", city: "관악구" },
  "11650": { province: "서울특별시", city: "서초구" },
  "11680": { province: "서울특별시", city: "강남구" },
  "11710": { province: "서울특별시", city: "송파구" },
  "11740": { province: "서울특별시", city: "강동구" },
  "12110": { province: "전남광주통합특별시", city: "목포시" },
  "12130": { province: "전남광주통합특별시", city: "여수시" },
  "12150": { province: "전남광주통합특별시", city: "순천시" },
  "12170": { province: "전남광주통합특별시", city: "나주시" },
  "12190": { province: "전남광주통합특별시", city: "광양시" },
  "12210": { province: "전남광주통합특별시", city: "동구" },
  "12240": { province: "전남광주통합특별시", city: "서구" },
  "12270": { province: "전남광주통합특별시", city: "남구" },
  "12300": { province: "전남광주통합특별시", city: "북구" },
  "12330": { province: "전남광주통합특별시", city: "광산구" },
  "12710": { province: "전남광주통합특별시", city: "담양군" },
  "12720": { province: "전남광주통합특별시", city: "곡성군" },
  "12730": { province: "전남광주통합특별시", city: "구례군" },
  "12740": { province: "전남광주통합특별시", city: "고흥군" },
  "12750": { province: "전남광주통합특별시", city: "보성군" },
  "12760": { province: "전남광주통합특별시", city: "화순군" },
  "12770": { province: "전남광주통합특별시", city: "장흥군" },
  "12780": { province: "전남광주통합특별시", city: "강진군" },
  "12790": { province: "전남광주통합특별시", city: "해남군" },
  "12800": { province: "전남광주통합특별시", city: "영암군" },
  "12810": { province: "전남광주통합특별시", city: "무안군" },
  "12820": { province: "전남광주통합특별시", city: "함평군" },
  "12830": { province: "전남광주통합특별시", city: "영광군" },
  "12840": { province: "전남광주통합특별시", city: "장성군" },
  "12850": { province: "전남광주통합특별시", city: "완도군" },
  "12860": { province: "전남광주통합특별시", city: "진도군" },
  "12870": { province: "전남광주통합특별시", city: "신안군" },
  "26110": { province: "부산광역시", city: "중구" },
  "26140": { province: "부산광역시", city: "서구" },
  "26170": { province: "부산광역시", city: "동구" },
  "26200": { province: "부산광역시", city: "영도구" },
  "26230": { province: "부산광역시", city: "부산진구" },
  "26260": { province: "부산광역시", city: "동래구" },
  "26290": { province: "부산광역시", city: "남구" },
  "26320": { province: "부산광역시", city: "북구" },
  "26350": { province: "부산광역시", city: "해운대구" },
  "26380": { province: "부산광역시", city: "사하구" },
  "26410": { province: "부산광역시", city: "금정구" },
  "26440": { province: "부산광역시", city: "강서구" },
  "26470": { province: "부산광역시", city: "연제구" },
  "26500": { province: "부산광역시", city: "수영구" },
  "26530": { province: "부산광역시", city: "사상구" },
  "26710": { province: "부산광역시", city: "기장군" },
  "27110": { province: "대구광역시", city: "중구" },
  "27140": { province: "대구광역시", city: "동구" },
  "27170": { province: "대구광역시", city: "서구" },
  "27200": { province: "대구광역시", city: "남구" },
  "27230": { province: "대구광역시", city: "북구" },
  "27260": { province: "대구광역시", city: "수성구" },
  "27290": { province: "대구광역시", city: "달서구" },
  "27710": { province: "대구광역시", city: "달성군" },
  "27720": { province: "대구광역시", city: "군위군" },
  "28110": { province: "인천광역시", city: "중구" },
  "28125": { province: "인천광역시", city: "제물포구" },
  "28140": { province: "인천광역시", city: "동구" },
  "28155": { province: "인천광역시", city: "영종구" },
  "28177": { province: "인천광역시", city: "미추홀구" },
  "28185": { province: "인천광역시", city: "연수구" },
  "28200": { province: "인천광역시", city: "남동구" },
  "28237": { province: "인천광역시", city: "부평구" },
  "28245": { province: "인천광역시", city: "계양구" },
  "28260": { province: "인천광역시", city: "서구" },
  "28275": { province: "인천광역시", city: "서해구" },
  "28290": { province: "인천광역시", city: "검단구" },
  "28710": { province: "인천광역시", city: "강화군" },
  "28720": { province: "인천광역시", city: "옹진군" },
  "30110": { province: "대전광역시", city: "동구" },
  "30140": { province: "대전광역시", city: "중구" },
  "30170": { province: "대전광역시", city: "서구" },
  "30200": { province: "대전광역시", city: "유성구" },
  "30230": { province: "대전광역시", city: "대덕구" },
  "31110": { province: "울산광역시", city: "중구" },
  "31140": { province: "울산광역시", city: "남구" },
  "31170": { province: "울산광역시", city: "동구" },
  "31200": { province: "울산광역시", city: "북구" },
  "31710": { province: "울산광역시", city: "울주군" },
  "36110": { province: "세종특별자치시" },
  "41111": { province: "경기도", city: "수원시", subdivision: "장안구" },
  "41113": { province: "경기도", city: "수원시", subdivision: "권선구" },
  "41115": { province: "경기도", city: "수원시", subdivision: "팔달구" },
  "41117": { province: "경기도", city: "수원시", subdivision: "영통구" },
  "41131": { province: "경기도", city: "성남시", subdivision: "수정구" },
  "41133": { province: "경기도", city: "성남시", subdivision: "중원구" },
  "41135": { province: "경기도", city: "성남시", subdivision: "분당구" },
  "41150": { province: "경기도", city: "의정부시" },
  "41171": { province: "경기도", city: "안양시", subdivision: "만안구" },
  "41173": { province: "경기도", city: "안양시", subdivision: "동안구" },
  "41192": { province: "경기도", city: "부천시", subdivision: "원미구" },
  "41194": { province: "경기도", city: "부천시", subdivision: "소사구" },
  "41196": { province: "경기도", city: "부천시", subdivision: "오정구" },
  "41210": { province: "경기도", city: "광명시" },
  "41220": { province: "경기도", city: "평택시" },
  "41250": { province: "경기도", city: "동두천시" },
  "41271": { province: "경기도", city: "안산시", subdivision: "상록구" },
  "41273": { province: "경기도", city: "안산시", subdivision: "단원구" },
  "41281": { province: "경기도", city: "고양시", subdivision: "덕양구" },
  "41285": { province: "경기도", city: "고양시", subdivision: "일산동구" },
  "41287": { province: "경기도", city: "고양시", subdivision: "일산서구" },
  "41290": { province: "경기도", city: "과천시" },
  "41310": { province: "경기도", city: "구리시" },
  "41360": { province: "경기도", city: "남양주시" },
  "41370": { province: "경기도", city: "오산시" },
  "41390": { province: "경기도", city: "시흥시" },
  "41410": { province: "경기도", city: "군포시" },
  "41430": { province: "경기도", city: "의왕시" },
  "41450": { province: "경기도", city: "하남시" },
  "41461": { province: "경기도", city: "용인시", subdivision: "처인구" },
  "41463": { province: "경기도", city: "용인시", subdivision: "기흥구" },
  "41465": { province: "경기도", city: "용인시", subdivision: "수지구" },
  "41480": { province: "경기도", city: "파주시" },
  "41500": { province: "경기도", city: "이천시" },
  "41550": { province: "경기도", city: "안성시" },
  "41570": { province: "경기도", city: "김포시" },
  "41590": { province: "경기도", city: "화성시" },
  "41591": { province: "경기도", city: "화성시", subdivision: "만세구" },
  "41593": { province: "경기도", city: "화성시", subdivision: "효행구" },
  "41595": { province: "경기도", city: "화성시", subdivision: "병점구" },
  "41597": { province: "경기도", city: "화성시", subdivision: "동탄구" },
  "41610": { province: "경기도", city: "광주시" },
  "41630": { province: "경기도", city: "양주시" },
  "41650": { province: "경기도", city: "포천시" },
  "41670": { province: "경기도", city: "여주시" },
  "41800": { province: "경기도", city: "연천군" },
  "41820": { province: "경기도", city: "가평군" },
  "41830": { province: "경기도", city: "양평군" },
  "43111": { province: "충청북도", city: "청주시", subdivision: "상당구" },
  "43112": { province: "충청북도", city: "청주시", subdivision: "서원구" },
  "43113": { province: "충청북도", city: "청주시", subdivision: "흥덕구" },
  "43114": { province: "충청북도", city: "청주시", subdivision: "청원구" },
  "43130": { province: "충청북도", city: "충주시" },
  "43150": { province: "충청북도", city: "제천시" },
  "43720": { province: "충청북도", city: "보은군" },
  "43730": { province: "충청북도", city: "옥천군" },
  "43740": { province: "충청북도", city: "영동군" },
  "43745": { province: "충청북도", city: "증평군" },
  "43750": { province: "충청북도", city: "진천군" },
  "43760": { province: "충청북도", city: "괴산군" },
  "43770": { province: "충청북도", city: "음성군" },
  "43800": { province: "충청북도", city: "단양군" },
  "44130": { province: "충청남도", city: "천안시" },
  "44131": { province: "충청남도", city: "천안시", subdivision: "동남구" },
  "44133": { province: "충청남도", city: "천안시", subdivision: "서북구" },
  "44150": { province: "충청남도", city: "공주시" },
  "44180": { province: "충청남도", city: "보령시" },
  "44200": { province: "충청남도", city: "아산시" },
  "44210": { province: "충청남도", city: "서산시" },
  "44230": { province: "충청남도", city: "논산시" },
  "44250": { province: "충청남도", city: "계룡시" },
  "44270": { province: "충청남도", city: "당진시" },
  "44710": { province: "충청남도", city: "금산군" },
  "44760": { province: "충청남도", city: "부여군" },
  "44770": { province: "충청남도", city: "서천군" },
  "44790": { province: "충청남도", city: "청양군" },
  "44800": { province: "충청남도", city: "홍성군" },
  "44810": { province: "충청남도", city: "예산군" },
  "44825": { province: "충청남도", city: "태안군" },
  "47111": { province: "경상북도", city: "포항시", subdivision: "남구" },
  "47113": { province: "경상북도", city: "포항시", subdivision: "북구" },
  "47130": { province: "경상북도", city: "경주시" },
  "47150": { province: "경상북도", city: "김천시" },
  "47170": { province: "경상북도", city: "안동시" },
  "47190": { province: "경상북도", city: "구미시" },
  "47210": { province: "경상북도", city: "영주시" },
  "47230": { province: "경상북도", city: "영천시" },
  "47250": { province: "경상북도", city: "상주시" },
  "47280": { province: "경상북도", city: "문경시" },
  "47290": { province: "경상북도", city: "경산시" },
  "47730": { province: "경상북도", city: "의성군" },
  "47750": { province: "경상북도", city: "청송군" },
  "47760": { province: "경상북도", city: "영양군" },
  "47770": { province: "경상북도", city: "영덕군" },
  "47820": { province: "경상북도", city: "청도군" },
  "47830": { province: "경상북도", city: "고령군" },
  "47840": { province: "경상북도", city: "성주군" },
  "47850": { province: "경상북도", city: "칠곡군" },
  "47900": { province: "경상북도", city: "예천군" },
  "47920": { province: "경상북도", city: "봉화군" },
  "47930": { province: "경상북도", city: "울진군" },
  "47940": { province: "경상북도", city: "울릉군" },
  "48121": { province: "경상남도", city: "창원시", subdivision: "의창구" },
  "48123": { province: "경상남도", city: "창원시", subdivision: "성산구" },
  "48125": { province: "경상남도", city: "창원시", subdivision: "마산합포구" },
  "48127": { province: "경상남도", city: "창원시", subdivision: "마산회원구" },
  "48129": { province: "경상남도", city: "창원시", subdivision: "진해구" },
  "48170": { province: "경상남도", city: "진주시" },
  "48220": { province: "경상남도", city: "통영시" },
  "48240": { province: "경상남도", city: "사천시" },
  "48250": { province: "경상남도", city: "김해시" },
  "48270": { province: "경상남도", city: "밀양시" },
  "48310": { province: "경상남도", city: "거제시" },
  "48330": { province: "경상남도", city: "양산시" },
  "48720": { province: "경상남도", city: "의령군" },
  "48730": { province: "경상남도", city: "함안군" },
  "48740": { province: "경상남도", city: "창녕군" },
  "48820": { province: "경상남도", city: "고성군" },
  "48840": { province: "경상남도", city: "남해군" },
  "48850": { province: "경상남도", city: "하동군" },
  "48860": { province: "경상남도", city: "산청군" },
  "48870": { province: "경상남도", city: "함양군" },
  "48880": { province: "경상남도", city: "거창군" },
  "48890": { province: "경상남도", city: "합천군" },
  "50110": { province: "제주특별자치도", city: "제주시" },
  "50130": { province: "제주특별자치도", city: "서귀포시" },
  "51110": { province: "강원특별자치도", city: "춘천시" },
  "51130": { province: "강원특별자치도", city: "원주시" },
  "51150": { province: "강원특별자치도", city: "강릉시" },
  "51170": { province: "강원특별자치도", city: "동해시" },
  "51190": { province: "강원특별자치도", city: "태백시" },
  "51210": { province: "강원특별자치도", city: "속초시" },
  "51230": { province: "강원특별자치도", city: "삼척시" },
  "51720": { province: "강원특별자치도", city: "홍천군" },
  "51730": { province: "강원특별자치도", city: "횡성군" },
  "51750": { province: "강원특별자치도", city: "영월군" },
  "51760": { province: "강원특별자치도", city: "평창군" },
  "51770": { province: "강원특별자치도", city: "정선군" },
  "51780": { province: "강원특별자치도", city: "철원군" },
  "51790": { province: "강원특별자치도", city: "화천군" },
  "51800": { province: "강원특별자치도", city: "양구군" },
  "51810": { province: "강원특별자치도", city: "인제군" },
  "51820": { province: "강원특별자치도", city: "고성군" },
  "51830": { province: "강원특별자치도", city: "양양군" },
  "52111": { province: "전북특별자치도", city: "전주시", subdivision: "완산구" },
  "52113": { province: "전북특별자치도", city: "전주시", subdivision: "덕진구" },
  "52130": { province: "전북특별자치도", city: "군산시" },
  "52140": { province: "전북특별자치도", city: "익산시" },
  "52180": { province: "전북특별자치도", city: "정읍시" },
  "52190": { province: "전북특별자치도", city: "남원시" },
  "52210": { province: "전북특별자치도", city: "김제시" },
  "52710": { province: "전북특별자치도", city: "완주군" },
  "52720": { province: "전북특별자치도", city: "진안군" },
  "52730": { province: "전북특별자치도", city: "무주군" },
  "52740": { province: "전북특별자치도", city: "장수군" },
  "52750": { province: "전북특별자치도", city: "임실군" },
  "52770": { province: "전북특별자치도", city: "순창군" },
  "52790": { province: "전북특별자치도", city: "고창군" },
  "52800": { province: "전북특별자치도", city: "부안군" },
};

/** Machine-readable provenance for `YOUTH_ZIPCD_CROSSWALK`. */
export const YOUTH_ZIPCD_CROSSWALK_PROVENANCE = {
  version: "2026-07-bjdong-full.1",
  effectiveAsOf: "2026-07-01",
  sourceType: "official_government_dataset" as const,
  sourceFilename: "법정동코드 전체자료.zip",
  sourceInnerFilename: "법정동코드 전체자료.txt",
  sourceEncoding: "cp949",
  sourceSha256: "7b4b544a6302d26c4f4c89d2c1355beae82e958c786bad8cc8572db0d2e2eb33",
  sourceInnerSha256: "8cfd829c797270b56243a46e9f1e4e95377c2135153c36909021a35a1e32966a",
  totalDataRows: 53387,
  observedZipCdTokens: 261,
  classification: {
    currentLeaf: 217,
    currentParentCity: 2,
    subordinateGu: 39,
    historicalAbolished: 3,
    unmapped: 0,
  },
  historicalTokens: {
    "28110": "인천광역시 중구 (폐지 2026-07-01)",
    "28140": "인천광역시 동구 (폐지 2026-07-01)",
    "28260": "인천광역시 서구 (폐지 2026-07-01)",
  },
  parentCityTokens: {
    "41590": "경기도 화성시 (parent-aggregate 법정동코드, distinct from its 4 subordinate-gu codes)",
    "44130": "충청남도 천안시 (parent-aggregate 법정동코드, distinct from its 2 subordinate-gu codes)",
  },
  verifiedAt: "2026-09-06",
  authoritative: true,
  note:
    "Supersedes ZIP_CD_PROVENANCE's prior 'code-system identity unverified' " +
    "verdict for a DIFFERENT source than the one that provenance record " +
    "documents (this is the 법정동코드 전체자료 government dataset, not " +
    "API코드정보.xlsx, which still genuinely lacks a zipCd family). All 261 " +
    "distinct zipCd tokens observed in the frozen 2,745-record Youth catalog " +
    "snapshot resolved with zero unmapped tokens; see " +
    "domain/region/subdivisionPartition.ts's PARENT_CITY_SUBDIVISION_PROVENANCE " +
    "for the same source's subdivision-partition derivation.",
};

/** Result of resolving one raw `zipCd` value (comma-delimited OR list) through the crosswalk. */
export interface YouthZipCdResolution {
  /** Deduplicated, resolved RegionSpecs — safe to use as a `region_in` rule's OR list only when `allResolved` is true. */
  specs: RegionSpec[];
  /** False if ANY raw token failed to resolve — callers must NOT build a partial rule from `specs` in that case (see file header on OR-branch safety). */
  allResolved: boolean;
  /** Raw tokens that failed to resolve (empty when `allResolved` is true). */
  unknownTokens: string[];
}

function specKey(spec: RegionSpec): string {
  return `${spec.province}|${spec.city ?? ""}|${spec.subdivision ?? ""}`;
}

/**
 * Parses a raw (possibly comma-delimited OR) `zipCd` value and resolves
 * every token through `YOUTH_ZIPCD_CROSSWALK`, deduplicating identical
 * resulting territories.
 *
 * Safety contract (checkpoint: Youth zipCd structured region eligibility):
 * if even ONE raw token fails to resolve (a genuinely unknown future code),
 * `allResolved` is false and callers must treat the ENTIRE region dimension
 * as unresolved — never silently drop the unknown branch and build a rule
 * from only the known subset, which could manufacture a false FAIL for a
 * user who would have matched via the missing branch.
 */
export function resolveYouthZipCd(raw: string | undefined): YouthZipCdResolution {
  const tokens = (raw ?? "")
    .split(",")
    .map((t) => t.trim())
    .filter(Boolean);

  const specs: RegionSpec[] = [];
  const seen = new Set<string>();
  const unknownTokens: string[] = [];

  for (const token of tokens) {
    const spec = YOUTH_ZIPCD_CROSSWALK[token];
    if (!spec) {
      unknownTokens.push(token);
      continue;
    }
    const key = specKey(spec);
    if (seen.has(key)) continue;
    seen.add(key);
    specs.push(spec);
  }

  return { specs, allResolved: unknownTokens.length === 0, unknownTokens };
}
